### ISSUE TITLE
KajikiSyntaxError not raised when a function gets called like ${echo('hello'))}

### ISSUE THREAD

**Issue by CastixGitHub** [nandoflorestan/kajiki#33]
I wrote a test in TestFunction in test_xml.py
```python
def test_function_call_double_parenthesis(self):
    perform('''<div py:strip="True"
><py:def function="echo(x)">$x</py:def
>${echo('hello'))}</div>''', 'hello')
```
it fails in this way:
```
FAIL: test_function_double_parenthesis (kajiki.tests.test_xml.TestFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/castix/axant/kajiki/kajiki/tests/test_xml.py", line 375, in test_function_double_parenthesis
    >${echo('hello'))}</div>''', 'hello')
  File "/home/castix/axant/kajiki/kajiki/tests/test_xml.py", line 78, in perform
    assert rsp == expected_output, (rsp, expected_output)
AssertionError: (u'hello}', u'hello')
-------------------- >> begin captured stdout << ---------------------

class template:
    @kajiki.expose
    def __main__():
        if not (True): yield u'<div>'
        yield self.__kj__.escape(echo('hello'))
        yield local.__kj__.gettext(u'}')
        if not (True): yield u'</div>'
    @kajiki.expose
    def echo(x):
        yield self.__kj__.escape(x)
template = kajiki.Template(template)
```

as the call is `${echo('hello'))}` i would expect a KajikiSyntaxError to be raised instead of have that extra `}`
Thanks :)

**Comment by amol-** [comment]
Fixed by https://github.com/nandoflorestan/kajiki/pull/38/files
